### ISSUE TITLE
Does Zalando HA on top of Rook Ceph HA result in redundant HA?

### ISSUE THREAD

**Issue by jfathman** [galexrt/owncloud-kubernetes-rook#1]
Thank you for this helpful example.

I have Zalando postgres-operator running postgres HA on three microk8s nodes using microk8s-hostpath local storage.  Zalando manages the postgres replicas, and failover works.

If I replace microk8s-hostpath local storage with rook ceph block storage, will that result in redundant replication?  Meaning, will Zalando still maintain postgres replicas across the cluster on its own, even though rook ceph is now maintaining block level replicas?

Or do I need to somehow configure Zalando to rely on the underyling rook ceph HA, and no longer maintain its own postgres replicas?

**Comment by galexrt** [comment]
The Zalando Postgres operator automatically replicates the data between the Postgres "nodes" if you have more than 1 Postgres pod in that Postgres cluster.

Using Rook Ceph block storage will cause the data to be replicated again, which would "waste space".

In the end you need to evaluate the performance and risks, e.g., "how reliable is my local storage vs Ceph block storage", comes to my mind.

**Comment by jfathman** [comment]
Thanks for confirming that situation.  Very helpful.
